trailingComma: es5
tabWidth: 4
semi: true
singleQuote: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrderParserPlugins:
  - 'typescript'
  - 'decorators-legacy'
importOrder:
  - <THIRD_PARTY_MODULES>
  - ^src/app/(.*)$
  - ^src/environments/(.*)$
  - '^\./(.*)$'
  - '^\.\./(.*)$'
importOrderSeparation: true
importOrderSortSpecifiers: true
overrides:
  - files:
      - '*.html'
      - '*.yml'
      - '*.json'
      - karma.conf.js
      - '*.spec.ts'
      - '*.md'
    options:
      tabWidth: 2
