trailingComma: es5
tabWidth: 4
semi: true
singleQuote: true
overrides:
  - files:
      - '*.html'
      - '*.yml'
      - '*.json'
      - karma.conf.js
      - '*.spec.ts'
      - '*.md'
    options:
      tabWidth: 2
